### ISSUE TITLE
The command "curve_ops_tool status" not working when deploy curvebs without snapshotclone service

### ISSUE THREAD

**Issue by legionxiong** [opencurve/curveadm#112]
root@curvebs-mds:/curvebs/mds# curve_ops_tool status
Split snapshot clone server address fail!
Init snapshotClient failed!
Init StatusTool failed

**Comment by Wine93** [comment]
> root@curvebs-mds:/curvebs/mds# curve_ops_tool status Split snapshot clone server address fail! Init snapshotClient failed! Init StatusTool failed

Yep, it is a bug, we will fix it in the `v0.0.27`.
