### ISSUE TITLE
deploy failed with errno -12

### ISSUE THREAD

**Issue by aspirer** [opencurve/curveadm#114]
retry may be success.

![b5a02deedf73cf3350ea095b177a1ec](https://user-images.githubusercontent.com/3424999/178895923-791dc617-4a01-4676-8881-ea3211c46296.png)
![0211e7e23319151934f8f6fadd9e5c2](https://user-images.githubusercontent.com/3424999/178895940-63ae5f30-c977-4050-9529-66560a702092.png)

**Comment by caoxianfei1** [comment]
The issue has been fixed for newer version.
