### ISSUE TITLE
root user without sudo failed ro tun some command

### ISSUE THREAD

**Issue by aspirer** [opencurve/curveadm#115]
![dabf6a6d64efc4d77226930111b80fa](https://user-images.githubusercontent.com/3424999/178896060-83de1669-d53c-4c62-9f50-cc0824429040.png)
![d1f82ad46f0617a8c5f2df66f832359](https://user-images.githubusercontent.com/3424999/178896111-be9ecbaa-a573-45dc-803f-241d61a44b05.png)

**Comment by caoxianfei1** [comment]
Set `sudo_alias = " "` to avoid it at `.curveadm/curveadm.cfg` configure file
