### ISSUE TITLE
curveadm format  fail,write fstab fail

### ISSUE THREAD

**Issue by YunhuiChen** [opencurve/curveadm#120]
1、debain11
pubbeta1-nostest1.yq.163.org 5.10.0-16-amd64 #1 SMP Debian 5.10.127-1 
2、
![image](https://user-images.githubusercontent.com/67582932/180144695-ac9ddb6f-93b5-45b1-9aa1-70b3688f1c03.png)

![image](https://user-images.githubusercontent.com/67582932/180144761-4ec43993-35fa-4ba2-859c-9851a0846a9b.png)

**Comment by caoxianfei1** [comment]
Close the issue and wait for it to reappear.
