### ISSUE TITLE
ssh: handshake failed: ssh

### ISSUE THREAD

**Issue by Waterman1997** [opencurve/curveadm#124]
`root@ubuntu:~/curve# curveadm deploy
Cluster Name    : my-cluster
Cluster Kind    : curvefs
Cluster Services: etcd*3, mds*3, metaserver*3

Pull Image: [ERROR]  
  + host=192.168.253.111  image=opencurvedocker/curvefs:latest [0/1] [ERROR]  
  + host=192.168.253.112  image=opencurvedocker/curvefs:latest [0/1] [ERROR]  
  + host=192.168.253.113  image=opencurvedocker/curvefs:latest [0/1] [ERROR]  
  + host=192.168.253.111  image=opencurvedocker/curvefs:latest [0/1] [ERROR]  
  + host=192.168.253.112  image=opencurvedocker/curvefs:latest [0/1] [ERROR]  
  + host=192.168.253.113  image=opencurvedocker/curvefs:latest [0/1] [ERROR]  
  + host=192.168.253.111  image=opencurvedocker/curvefs:latest [0/1] [ERROR]  
  + host=192.168.253.112  image=opencurvedocker/curvefs:latest [0/1] [ERROR]  
  + host=192.168.253.113  image=opencurvedocker/curvefs:latest [0/1] [ERROR]  
Error: 
ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
See log file for detail: /root/.curveadm/logs/curveadm-2022-07-23_08-53-26.log
root@ubuntu:~/curve# cat /root/.curveadm/logs/curveadm-2022-07-23_08-53-26.log | tail -n 1
[2022/07/23 08:53:26.325 +00:00] [ERROR] [ssh.go:92] [SSHConnect] [user=root] [addr=192.168.253.112:22] [PrivateKeyPath=/root/.ssh/id_rsa] [error="ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain"]
root@ubuntu:~/curve# ssh root@192.168.253.112 -p 22 -i /root/.ssh/id_rsa
**connection succeeded**
`

`root@ubuntu:~/curve# ssh -V
OpenSSH_8.9p1 Ubuntu-3, OpenSSL 3.0.2 15 Mar 2022
root@ubuntu:~/curve# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04 LTS
Release:	22.04
Codename:	jammy
`

**Comment by Wine93** [comment]
@Waterman1997 can you provide the global section of your `topology`?

**Comment by Waterman1997** [comment]
> @Waterman1997 can you provide the global section of your `topology`?

Sorry, I have cleaned the environment
Some useful information as above
