### ISSUE TITLE
 Determine if a mirror exists locally

### ISSUE THREAD

**Issue by gorquan** [opencurve/curveadm#129]
此处提供个建议
在curveadm format时，应该加上判断本地是否存在镜像
对于网络不好的用户，经常性出现`Error response from daemon: Get \"https://registry-1.docker.io/v2/\": net/http: TLS handshake timeout`，但是本地已经存在镜像，无拉取镜像的必要
![image](https://user-images.githubusercontent.com/21988227/184687248-691afc84-c543-4d21-a712-cb26bbc62951.png)
![image](https://user-images.githubusercontent.com/21988227/184687302-42366ef4-4776-4e4c-b2be-544d7de1e2ce.png)

**Comment by caoxianfei1** [comment]
`docker pull` 能够根据镜像的digest判断本地镜像是否存在，如果digest一致的话则不会重新pull。出现上述问题的原因可能是因为registry中的镜像更新了。
