### ISSUE TITLE
update wiki - about curveadm hosts command

### ISSUE THREAD

**Issue by gorquan** [opencurve/curveadm#130]
wiki中存在问题，在导入主机列表章节，有个命令`curveadm hosts...`，但最新版本不再存在该命令，应该对wiki进行更新，避免误导
![image](https://user-images.githubusercontent.com/21988227/184687765-1327388a-c836-429d-acc7-28fc2fa6eae2.png)
![image](https://user-images.githubusercontent.com/21988227/184687811-e0f1a305-c7a0-4b0f-b151-e70714e40afb.png)

**Comment by gorquan** [comment]
解决该问题，将`user`、`ssh_port`、`private_key_file`卸载topology.yaml的global处，可实现相同功能
![image](https://user-images.githubusercontent.com/21988227/184688131-95381a41-cfff-4bb0-a4d5-e47829ad1b5d.png)

**Comment by Wine93** [comment]
> wiki中存在问题，在导入主机列表章节，有个命令`curveadm hosts...`，但最新版本不再存在该命令，应该对wiki进行更新，避免误导 ![image](https://user-images.githubusercontent.com/21988227/184687765-1327388a-c836-429d-acc7-28fc2fa6eae2.png) ![image](https://user-images.githubusercontent.com/21988227/184687811-e0f1a305-c7a0-4b0f-b151-e70714e40afb.png)

我们这 2 天在调试 WiKi，有可能造成了 WiKi 和 CurveAdm 版本的不一致，现在我们已调试完毕，你可以重新安装 CurveAdm，并按照 WiKi 指引一步步完成部署 :)

**Comment by caoxianfei1** [comment]
Close this issue because there has been no reply for a long time.
