### ISSUE TITLE
CentOS 9: [curveadm deploy] Start Mock HTTP Server <network>: [ERROR]

### ISSUE THREAD

**Issue by yongshengma** [opencurve/curveadm#139]
我正在CentOS 9 上安装curvefs，其中遇到的一个问题是卡在：Start Mock HTTP Server <network>: [ERROR]。通过看log发现是在各host节点上未能成功执行docker 下载，手动在各节点上执行下载以后即可。能否指点一下在 curveadm 这里应该修改哪个地方，以便我自己能修正deploy相关的脚本或代码。

**Comment by caoxianfei1** [comment]
因为长时间未回复暂时关闭这个issue.
