### ISSUE TITLE
[develop activities] misunderstand of replica in topology.yaml

### ISSUE THREAD

**Issue by ilixiaocui** [opencurve/curveadm#146]
https://github.com/opencurve/curveadm/wiki/topology#replica

Maybe it's better to use `instances` or `servicenum` instead of `replica`.

**Comment by zhanghuidinah** [comment]
- **This issue has been chosen for community developer activities.  Welcome to feel free to try it. After the PR is merged, you will receive a gift package and a certificate as a community contributor.**

- **Developer Activities Registration Steps please ref https://github.com/opencurve/curve/issues/2334#issuecomment-1504723771**

**Comment by tiansuo114** [comment]
I want to assign this issue

**Comment by caoxianfei1** [comment]
> I want to assign this issue

done
