### ISSUE TITLE
[Curveadm] Specify blocksize when mounting the curvebs volume by target

### ISSUE THREAD

**Issue by cw123** [opencurve/curveadm#150]
When using curveadm to mount the curvebs volume by target, add a parameter to specify the default block size of the volume.

blocksize can be specified by the --blocksize parameter when adding luns to tgtadm.

使用curveadm通过target的方式挂载curvebs 卷的时候，添加一个参数，可以指定卷默认的block size。

blocksize可以在tgtadm 添加lun的时候，通过--blocksize 参数指定。

The corresponding code is in curveadm：

对应的代码在curveadm的：

 https://github.com/opencurve/curveadm/blob/master/internal/task/scripts/target.go。

for example:

举个例子：

```
tgtadm --lld iscsi \
     --tid ${g_tid} \
     --lun 1 \
     --bstype curve \
    --backing-store ${g_image} \
    --blocksize 4096   # add blocksize here
```

Require:

1. The blocksize is consistent with the global.alignment.commonVolume of client.conf. curveadm reads the global.alignment.commonVolume field of client.conf and sets blocksize.
2. Perform a simple check on this field, which must be an integer multiple of 512.

要求：

1. blocksize 和client.conf的 global.alignment.commonVolume 保持一致。curveadm读取client.conf的global.alignment.commonVolume字段，设置blocksize。
2. 对这个字段进行简单校验，必须为512的整数倍。

**Comment by mfordjody** [comment]
assign to me
