### ISSUE TITLE
feature: All operation commands need to be recorded to the log file for audit

### ISSUE THREAD

**Issue by aspirer** [opencurve/curveadm#16]
All operation commands need to be recorded to the log file for follow-up audit operation steps.

**Comment by Wine93** [comment]
> All operation commands need to be recorded to the log file for follow-up audit operation steps.

Should all commands output to one file?

**Comment by aspirer** [comment]
> > All operation commands need to be recorded to the log file for follow-up audit operation steps.
> 
> Should all commands output to one file?

Sure, just like syslog, all user commands are logged in it.
