### ISSUE TITLE
[Feature] support incremental formatting

### ISSUE THREAD

**Issue by Cyber-SiKu** [opencurve/curveadm#189]
`format` 用于生成 chunkfile pool 用户提升 CurveBS 的性能，目前我们的 format 命令只支持全量格式化。这将导致用户在发现目前格式化的百分比过小时，只能重头开始格式化，这将消耗用户大量的时间。
我们希望你能帮我们实现增量格式化，以缩短用户部署的时间。为此，你可能需要了解下格式化相关的命令以及 curveadm `format` 命令相关的逻辑。
虽然这个工作量也许并不大，但是却会很大程度帮助我们提升用户的使用体验。

**Comment by zhanghuidinah** [comment]
- **This issue has been chosen for community developer activities.  Welcome to feel free to try it. After the PR is merged, you will receive a gift package and a certificate as a community contributor.**

- **Developer Activities Registration Steps please ref https://github.com/opencurve/curve/issues/2334#issuecomment-1504723771**

**Comment by liuminjian** [comment]
I would like to try this issue.

**Comment by caoxianfei1** [comment]
welcome!
