### ISSUE TITLE
[wiki] deploy memcache

### ISSUE THREAD

**Issue by Wine93** [opencurve/curveadm#200]
see [deploy_memcached](https://github.com/Cyber-SiKu/curveadm/wiki/deploy_memcached).

**Comment by Wine93** [comment]
一些建议：
* 可以简述下 memcache 的作用
* 内容结构可以调整，分为以下 2 块内容：
   * 部署 memcached: 部署步骤可以跟 wiki 中其他组件的部署保持一致，以步骤为引导，标明每一个步骤的作用
   * 操作运维：其他操作，包括停止、清理可以作为常规运维操作

**Comment by Cyber-SiKu** [comment]
> 一些建议：
> 
> * 可以简述下 memcache 的作用
> * 内容结构可以调整，分为以下 2 块内容：
>   
>   * 部署 memcached: 部署步骤可以跟 wiki 中其他组件的部署保持一致，以步骤为引导，标明每一个步骤的作用
>   * 操作运维：其他操作，包括停止、清理可以作为常规运维操作

update
