### ISSUE TITLE
[bug] sed command error when format 

### ISSUE THREAD

**Issue by ethanas** [opencurve/curveadm#216]
执行 curveadm format时，替换/etc/fstab过程中传入的磁盘uuid前面有个换行，导致sed命令执行失败。
错误明细：

[ERR]:  (log.go:109):   Execute command
    remoteAddr: xxxxxxxxx
    command: sudo sed --in-place --expression='/UUID=
1f249102-8b6f-4019-90e6-3ce09d91598a/d' /etc/fstab
    output: sed: -e expression #1, char 6: unterminated address regex
    error: Process exited with status 1

**Comment by caoxianfei1** [comment]
the problem has been fixed and close the issue.
