### ISSUE TITLE
[bug] curveadm show wrong status of the cluster

### ISSUE THREAD

**Issue by chengyu-l** [opencurve/curveadm#217]
I get different the cluster status every time I execute _**curveadm status -v**_  command. Actually,  The cluster is healthy , I excute **_curvefs_tool status_** command to check.

execute time: 20230425
![image](https://user-images.githubusercontent.com/21003538/234504017-40630aa9-9e2f-4a56-86e0-fff45a840205.png)

execute time: 20230426
![image](https://user-images.githubusercontent.com/21003538/234503899-8ba7f402-6c96-4a20-a440-7ad3f5107877.png)

log 
![image](https://user-images.githubusercontent.com/21003538/234506178-8a9a05fd-0876-4535-a1c6-60dd186351d1.png)

**Comment by caoxianfei1** [comment]
It may to sudo command need to type passward for 'sudo: no tty present and no askpass program specified'
