### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by pppwaw** [opencurve/curveadm#219]
https://github.com/opencurve/curveadm/wiki/install-curveadm#%E8%BD%AF%E7%A1%AC%E4%BB%B6%E7%8E%AF%E5%A2%83%E9%9C%80%E6%B1%82
`QUME` -> `QEMU`

**Comment by Wine93** [comment]
> https://github.com/opencurve/curveadm/wiki/install-curveadm#%E8%BD%AF%E7%A1%AC%E4%BB%B6%E7%8E%AF%E5%A2%83%E9%9C%80%E6%B1%82 `QUME` -> `QEMU`

Thx @pppwaw, we fixed it.

**Comment by pppwaw** [comment]
Nice, thank you.
