### ISSUE TITLE
《快速上手 CurveAdm 开发》文档加上cobra框架说明

### ISSUE THREAD

**Issue by 284050768** [opencurve/curveadm#265]
我以前没接触过cobra和不知道本项目基于cobra框架开发，在开始时看源码相当吃力，后来在注释里了解到cobra框架，看完cobra的wiki后回来看代码一切都so easy！所以在《快速上手 CurveAdm 开发》文档里建议加上基于cobra框架相关说明及学习链接。

## Registration procedure
Step 1. Add a comment when you sign up.The purpose of comments is for us to understand you and determine whether you have the basic ability to complete this issue. 

- If you are a student, please introduce your school, major, programming language, technical fields of interest, what you are good at, and why you chose this issue. 
- If you are already working, please introduce your company, career, work content, technical fields of interest, and why you chose this issue.

Step 2. Use WeChat to add the Curve community assistant "Curve" as a WeChat friend, tell your GitHub ID, and send the Issue link of your choice. The assistant will invite you to communicate with the mentor  by WeChat.

Step 3. In order to better complete each development task, the mentor will select the developer who best matches the issue based on everyone's comment on GitHub and communication status by WeChat. If you are not selected, please select another issue.

## Tips
- Before developing, please read the dev guideline( https://ask.opencurve.io/t/topic/201) carefully and communicate with your mentor.
- Please submit a draft PR before 11.29, and the mentor will review it within 2-5 working days and may guide you to modify the PR based on the actual situation.
- If you successfully merge into PR before 12.27 and you will receive gifts carefully prepared by the Curve community.

**Comment by hdbdn77** [comment]
是需要介绍一下cobra框架，以及使用本项目的部分代码进行说明吗，如果是的话，我想试试。

**Comment by caoxianfei1** [comment]
> 是需要介绍一下cobra框架，以及使用本项目的部分代码进行说明吗，如果是的话，我想试试。

是的
