### ISSUE TITLE
[630001] pull image failed(docker pull IMAGE)

### ISSUE THREAD

**Issue by quas-modo** [opencurve/curveadm#273]
![Pasted image 20230707020646](https://github.com/opencurve/curveadm/assets/91517920/3925a512-38ce-4461-824f-fddedee33b23)

command: curveadm playground run --kind curvebs
version: v0.2.0
os: ubuntu22.04
logs: just as the image
Error-Code: 630001
Error-Description: pull iamge failed(docker pull IMAGE)
Error-Clue: `Error response from daemon: error parsing HTTP 403 response body: invalid character '<‘ looking fro  beginning of value: "<html>\r\n<head><title>403 Forbidden</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>403 Forbidden</h1></center>...`

**Comment by Wine93** [comment]
我们通过 help 信息可以看到运行的默认镜像是 `harbor.cloud.netease.com/curve/curvebs:playground`，这个镜像仓库是网易搭建运维，出于安全考虑目前已停止对外开放，你可以通过 `-i` 参数指定运行公共仓库镜像：

```bash
curveadm playground run -i opencurvedocker/curvebs:playground
```

**Comment by quas-modo** [comment]
Thank you! I've already fixed the problem.
