### ISSUE TITLE
[bug]curveadm target start will timeout

### ISSUE THREAD

**Issue by Cyber-SiKu** [opencurve/curveadm#291]
when run curveadm as follow
```bash
curveadm target add
```
it will timeout.

Does not affect the execution of subsequent commands

curveadm: 0.3.0

You should help us find out the reason and fix it.

## Registration procedure
Step 1. Add a comment when you sign up.The purpose of comments is for us to understand you and determine whether you have the basic ability to complete this issue. 

- If you are a student, please introduce your school, major, programming language, technical fields of interest, what you are good at, and why you chose this issue. 
- If you are already working, please introduce your company, career, work content, technical fields of interest, and why you chose this issue.

Step 2. Use WeChat to add the Curve community assistant "Curve" as a WeChat friend, tell your GitHub ID, and send the Issue link of your choice. The assistant will invite you to communicate with the mentor  by WeChat.

Step 3. In order to better complete each development task, the mentor will select the developer who best matches the issue based on everyone's comment on GitHub and communication status by WeChat. If you are not selected, please select another issue.

## Tips
- Before developing, please read the dev guideline( https://ask.opencurve.io/t/topic/201) carefully and communicate with your mentor.
- Please submit a draft PR before 11.29, and the mentor will review it within 2-5 working days and may guide you to modify the PR based on the actual situation.
- If you successfully merge into PR before 12.27 and you will receive gifts carefully prepared by the Curve community.

**Comment by hdbdn77** [comment]
curveadm: 0.3.0是什么版本，我在tags中没有找到，而且curveadm target add 该命令没有添加参数会提示requires exactly 1 argument,并不会time out。

**Comment by jaydee029** [comment]
Hi , I would like to work on this
I am a third year student pursuing Information Technology Engineering at MAIT, Delhi
I like to work on backend systems and CLIs, I have worked with c++ , Golang, js(node) and python.
Since this involves debugging and logic building I think this would be best suited for me.

**Comment by Subzeroo7** [comment]
> Hi , I would like to work on this I am a third year student pursuing Information Technology Engineering at MAIT, Delhi I like to work on backend systems and CLIs, I have worked with c++ , Golang, js(node) and python. Since this involves debugging and logic building I think this would be best suited for me. @hdbdn77
> 
> I would like to mention, wechat can't be accessed in India , can there be an alternate arrangement for the further steps.

You can directly explain your development ideas for this issue through comments, and the mentor @caoxianfei1  will confirm whether your solution is feasible. If it works, he'll assign it for you. Btw please pay attention to our event deadlines.

**Comment by caoxianfei1** [comment]
> curveadm: 0.3.0是什么版本，我在tags中没有找到，而且curveadm target add 该命令没有添加参数会提示requires exactly 1 argument,并不会time out。

see https://github.com/opencurve/curveadm/pull/243

**Comment by jaydee029** [comment]
Hi , so i was looking into the project but I couldn't find proper english docs for curveadm, can you link some helpful resources.

**Comment by hdbdn77** [comment]
> 您好，我正在研究该项目，但我找不到 curveadm 的正确英文文档，您可以链接一些有用的资源。@Subzeroo7 @caoxianfei1

You can use the Google Translate plugin to read wikis

**Comment by caoxianfei1** [comment]
> > 您好，我正在研究该项目，但我找不到 curveadm 的正确英文文档，您可以链接一些有用的资源。@Subzeroo7 @caoxianfei1
> 
> You can use the Google Translate plugin to read wikis

 Sorry, We don't have English documentation yet and you can try to translate it.

**Comment by zztaki** [comment]
Awesome Camp! I want to try it!

**Comment by caoxianfei1** [comment]
> Awesome Camp! I want to try it! I am a second-year graduate student from Huazhong University of Science and Technology. My research direction is storage systems and caching systems. I am now trying to apply emerging caching algorithms to ceph's bluestore. I'm eager to try curve to learn more about storage systems. Here is my [CV](https://zztaki.github.io/CV/CV.pdf).

Welcome!

**Comment by caoxianfei1** [comment]
We close it because we has fix it see https://github.com/opencurve/curveadm/pull/364. Everyone can open it again if you encounter the problem.
