### ISSUE TITLE
[功能问题]目前是否支持AppendECFile

### ISSUE THREAD

**Issue by zzjzhijun** [opencurve/curveadm#307]
您好，

我的项目中有大量的日志型的数据需要存储，所以希望使用AppendECFile的数据组织形式创建Curve集群，不知当前的版本是否能够支持？

期待回答。

**Comment by aspirer** [comment]
目前还不支持，EC方案初稿已完成设计，但开发由于人手问题，目前delay中，完成时间不确定。

**Comment by aspirer** [comment]
对于日志型的数据存储，一般推荐使用elasticsearch或者clickhouse这类存储系统来解决，curvefs可以作为此类存储系统的冷数据存储服务来达成降本提效的效果。可以参考这篇文章：https://zhuanlan.zhihu.com/p/598332479
