### ISSUE TITLE
先部署控制台再部署集群的操作路径有问题

### ISSUE THREAD

**Issue by w7team** [opencurve/curveadm#312]
![1695065817975](https://github.com/opencurve/curveadm/assets/74588507/2fc1c28c-fa70-4086-87d7-514609d1c175)
我看文档里说，是支持先部署控制台，然后再进入控制台操作部署集群的，这么操作发现卡在获取host信息这一步。
按理说控制台属于独立的服务，也不需要事先安装集群，为什么还要先导入host呢？

![image](https://github.com/opencurve/curveadm/assets/74588507/ec2124a8-0a0c-4a9f-8694-94d875da9665)

**Comment by caoxianfei1** [comment]
you can open an issue at repo curve-manager.
