### ISSUE TITLE
curveadm enter command can directly enter the leader container

### ISSUE THREAD

**Issue by caoxianfei1** [opencurve/curveadm#324]
现在我们想要进入leader容器的话，需要使用curveadm status查看leader容器的id，然后使用curveadm enter <id>进入，现在我们或许可以使用curveadm enter不用输入id的话就默认进入leader容器。

## Registration procedure
Step 1. Add a comment when you sign up.The purpose of comments is for us to understand you and determine whether you have the basic ability to complete this issue. 

- If you are a student, please introduce your school, major, programming language, technical fields of interest, what you are good at, and why you chose this issue. 
- If you are already working, please introduce your company, career, work content, technical fields of interest, and why you chose this issue.

Step 2. Use WeChat to add the Curve community assistant "Curve" as a WeChat friend, tell your GitHub ID, and send the Issue link of your choice. The assistant will invite you to communicate with the mentor  by WeChat.

Step 3. In order to better complete each development task, the mentor will select the developer who best matches the issue based on everyone's comment on GitHub and communication status by WeChat. If you are not selected, please select another issue.

## Tips
- Before developing, please read the dev guideline( https://ask.opencurve.io/t/topic/201) carefully and communicate with your mentor.
- Please submit a draft PR before 11.29, and the mentor will review it within 2-5 working days and may guide you to modify the PR based on the actual situation.
- If you successfully merge into PR before 12.27 and you will receive gifts carefully prepared by the Curve community.

**Comment by LYPWYT** [comment]
As a graduate student from the University of Electronic Science and Technology of China, I have gained a thorough understanding of the Kubernetes (K8s) system, which is open-sourced by Google. In relation to the aforementioned issue, I have the following ideas:
When executing the curveadm enter command without specifying a container ID as a parameter, we can implement a function that automatically calls the curveadm status command to retrieve the ID of the leader container, and then use this ID as a parameter to enter the leader container.

**Comment by caoxianfei1** [comment]
@LYPWYT Maybe you can refer to this curveadm status command to get the leader id, but calling this command may not be a good choice.

**Comment by tiansuo114** [comment]
Hello, I would like to apply to complete this topic. I will describe the general idea of the topic below.

I observed that getClusterMdsLeader is used in the displayStatus() function in the status.go file. I guess that a similar method can be used to obtain the id of the leader node in enter and detect it through the input after curveadm enter. If the specified id is not entered, call this method to obtain the mds leader id and try to connect.

The above is my general idea about this topic. There may still be many problems (such as misunderstanding whether the leader node is an mds leader node, whether the getClusterMdsLeader method can be called correctly, etc. and logical errors where the code is not well understood), but I still hope to get The instructor’s corrections and the opportunity to complete this question, and hope to participate in this development activity

**Comment by caoxianfei1** [comment]
> Hello, I would like to apply to complete this topic. I will describe the general idea of the topic below.
> 
> I observed that getClusterMdsLeader is used in the displayStatus() function in the status.go file. I guess that a similar method can be used to obtain the id of the leader node in enter and detect it through the input after curveadm enter. If the specified id is not entered, call this method to obtain the mds leader id and try to connect.
> 
> The above is my general idea about this topic. There may still be many problems (such as misunderstanding whether the leader node is an mds leader node, whether the getClusterMdsLeader method can be called correctly, etc. and logical errors where the code is not well understood), but I still hope to get The instructor’s corrections and the opportunity to complete this question, and hope to participate in this development activity

The issue has assigned to @LYPWYT . you can choose another.
