### ISSUE TITLE
420000  volume already mapped

### ISSUE THREAD

**Issue by yunwoniu** [opencurve/curveadm#326]
420000  volume already mapped
![image](https://github.com/opencurve/curveadm/assets/78011553/3972cad6-1045-479a-a92e-0362a51d5176)

命令 curveadm map hsy:/hsytest --host server-host1 -c client.yaml
CurveAdm v0.2.0
docker version 24.0.7
os：Linux debian 4.19.0-25-amd64 #1 SMP Debian 4.19.289-2 (2023-08-08) x86_64 GNU/Linux

![image](https://github.com/opencurve/curveadm/assets/78011553/ab2a5c00-c4c8-4bb3-bfcb-0915c5f163bf)

**Comment by caoxianfei1** [comment]
@yunwoniu curveadm version is old, install docker v1.19 is ok!

**Comment by Wine93** [comment]
> @yunwoniu curveadm version is old, install docker v1.19 is ok!

OR you can upgrade curveadm to v0.3.0, try it:

```bash
CURVEADM_VERSION=v0.3.0-rc10 curveadm -u
```

**Comment by yunwoniu** [comment]
@caoxianfei1 @Wine93  非常感谢，使用CURVEADM_VERSION=v0.3.0-rc10 curveadm -u  已经升级成功
