### ISSUE TITLE
420003 create volume failed ，卷map失败

### ISSUE THREAD

**Issue by yunwoniu** [opencurve/curveadm#347]
![image](https://github.com/opencurve/curveadm/assets/78011553/d44c1e73-6093-47b6-ae19-e04491756f65)
command: curveadm client map
version: CurveAdm v0.3.0
docker version: Docker version 24.0.7, build afdd53b

**Comment by caoxianfei1** [comment]
@yunwoniu can you provide the error log and help to locate the clue.
