### ISSUE TITLE
feature: Hope to provide upgrade features

### ISSUE THREAD

**Issue by baijiaruo** [opencurve/curveadm#42]
I hope to upgrade the curvefs cluster that has been installed, but I have found that there are no relevant steps and effective upgrade methods.

**Comment by yuchen-sun** [comment]
+1

**Comment by yuchen-sun** [comment]
BS also needs this feature

**Comment by Wine93** [comment]
> BS also needs this feature

It will coming soon, you can run `curveadm upgrade -h` for some preview.

**Comment by Wine93** [comment]
now we support upgrade all services, run `curveadm upgrade -h` for more information.
