### ISSUE TITLE
[request help] more flexible format.yaml

### ISSUE THREAD

**Issue by Wine93** [opencurve/curveadm#60]

**Comment by yuchen-sun** [comment]
hi @Wine93 
Could you describe it in detail?

**Comment by Wine93** [comment]
> hi @Wine93 Could you describe it in detail?

We will support the regex for `device` and `mount point`, like:

* format device from `/dev/sdb` to `/dev/sdk`:
```
 /dev/sd[b-k],/data/chunkserver[0-9],90
```

* skip device `/dev/sdd`:
```
 /dev/sd[b-k,^d],/data/chunkserver[0-9],90
```

If you have any idea about this, please tell us.

**Comment by aspirer** [comment]
> > hi @Wine93 Could you describe it in detail?
> 
> We will support the regex for `device` and `mount point`, like:
> 
> * format device from `/dev/sdb` to `/dev/sdk`:
> 
> ```
>  /dev/sd[b-k],/data/chunkserver[0-9],90
> ```
> 
> * skip device `/dev/sdd`:
> 
> ```
>  /dev/sd[b-k,^d],/data/chunkserver[0-9],90
> ```
> 
> If you have any idea about this, please tell us.

may be the chunkserver mount path can be generated in sequence(refer the disk sequence), do not need to be specified manually.
