### ISSUE TITLE
should check volume-name format while mapping nbd

### ISSUE THREAD

**Issue by aspirer** [opencurve/curveadm#64]
`$ curveadm map <user>:<volume-name> -c client.yaml --create --size 10GB`
`<volume-name>` must be start with '/' , but many users ignored it even we describe this note in manual.

so I think we should add some checks about the format of `<volume-name>`, such as if it is not start with '/', we print some error messages to users to suggest them using correct format.

**Comment by aspirer** [comment]
https://github.com/opencurve/curveadm/wiki/curvebs-client-deployment#%E7%AC%AC-3-%E6%AD%A5%E6%98%A0%E5%B0%84-curvebs-%E5%8D%B7

**Comment by Wine93** [comment]
> `$ curveadm map <user>:<volume-name> -c client.yaml --create --size 10GB` `<volume-name>` must be start with '/' , but many users ignored it even we describe this note in manual.
> 
> so I think we should add some checks about the format of `<volume-name>`, such as if it is not start with '/', we print some error messages to users to suggest them using correct format.

agree!

**Comment by aspirer** [comment]
after this change the prompt message is like this:
```
hzwangpan@pubbeta2-curve101:~$ ./curveadm map wp:vol2 -c client.yaml --create --size 1000GB
Error: invalid volume format, image name must start with /
```
