### ISSUE TITLE
request help: support deploy prometheus/grafana

### ISSUE THREAD

**Issue by aspirer** [opencurve/curveadm#73]
currently we can deploy prometheus/grafana with docker-compose, but the target.json can not be generated and updated automaticly, we need to deploy them by curveadm and support generating and updating target.json.

**Comment by aspirer** [comment]
Is it better to add a exporter http api to mds, then prometheus can get all endpoints automatically?

**Comment by aspirer** [comment]
we may just supporting to update prometheus config automatically(target.json), that is all we should do.

**Comment by caoxianfei1** [comment]
The issue is completed.
