### ISSUE TITLE
Need a flag 'enableSumInDir' in client.yaml to repalce default value in tools.conf

### ISSUE THREAD

**Issue by SeanHai** [opencurve/curveadm#74]

**Comment by Cyber-SiKu** [comment]
Does this configuration item have to be modified? If it is not necessary to modify, please set the default options in the curve. To modify the default value, please add a parameter with the same name in client.yaml.

**Comment by Cyber-SiKu** [comment]
just do like this:
<img width="318" alt="image" src="https://user-images.githubusercontent.com/15775037/157361978-40a9b8e5-4dbb-479b-a70b-4681a4097dc3.png">

<img width="223" alt="image" src="https://user-images.githubusercontent.com/15775037/157361925-7a2cb558-8182-4cdd-ba0d-c08dacd53765.png">
